name: Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Increase jar version
        working-directory: ./my-app
        run: mvn versions:set -DnewVersion=1.0.${{ vars.VERSION }}

      - name: Compile and Package
        working-directory: ./my-app
        run: mvn clean package

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-artifact
          path: my-app/target/my-app-1.0.${{ vars.VERSION }}.jar
        

  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
    - name: version increanent
      uses: action-pack/increment@v2
      with:
        name: 'VERSION'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}