name: Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Increase jar version
        working-directory: ./my-app
        run: mvn versions:set -DnewVersion=1.0.${{ vars.VERSION }}

      - name: Compile and Package
        working-directory: ./my-app
        run: mvn clean package

#      - name: Create artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: my-app-artifact
#          path: my-app/target/my-app-1.0.${{ vars.VERSION }}.jar
     
      - name: Create artifact
        run: cp ./my-app/target/my-app-1.0.${{ vars.VERSION }}.jar ./my-app-artifact.jar
      
      - name: Build Docker image
        run: docker build -t my-app:1.0.${{ vars.VERSION }} .

      - name: Tag Docker image
        run: docker tag my-app:1.0.${{ vars.VERSION }} adirwaitzman/my-app:1.0.${{ vars.VERSION }}
       
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Push Docker image to Docker Hub (Publish)
        run: docker push adirwaitzman/my-app:1.0.${{ vars.VERSION }}
  
      - name: run the docker image (deploy)
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ${{secrets.USER_NAME}}@$${{secrets.IP_ADDRESS}} '

            docker pull adirwaitzman/my-app:1.0.${{ vars.VERSION }}
            docker run adirwaitzman/my-app:1.0.${{ vars.VERSION }}
            '

        

  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
    - name: version increanent
      uses: action-pack/increment@v2
      with:
        name: 'VERSION'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}